print("Calculator Application")
print("--------------------")
x = float(input("Number X: "))
y = float(input("Number Y: "))
print("--------------------")
print("Result of Number X+Y is:",int(x+y))
print("Result of Number X-Y is:",int(x-y))
print("Result of Number X*Y is:",int(x*y))
print("Result of Number X/Y is:",int(x/y))